# https://github.com/rust-lang/rust-clippy/issues/9801
ignore-interior-mutability = ["bytes::Bytes", "bytestring::ByteString", "http::header::HeaderName", "http::header::HeaderValue"]
# Sometimes we want to keep the mod.rs file clean
allow-private-module-inception = true
