[package]
name = "restate-bifrost"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[features]
options_schema = ["dep:schemars"]

[dependencies]
restate-types = { workspace = true }

arc-swap = { workspace = true }
bytes = { workspace = true }
bytestring = { workspace = true, features = ["serde"] }
codederror = { workspace = true }
derive_builder = { workspace = true }
derive_more = { workspace = true }
drain = { workspace = true }
futures = { workspace = true }
schemars = { workspace = true, optional = true }
serde = { workspace = true }
serde_json = { workspace = true }
static_assertions = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }


[dev-dependencies]
restate-test-util = { workspace = true }

test-log = { workspace = true }
tracing-subscriber = { workspace = true }
