[package]
name = "restate-bifrost"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[features]
options_schema = ["dep:schemars"]
memory_loglet = []

[dependencies]
restate-core = { workspace = true }
restate-types = { workspace = true }

anyhow = { workspace = true }
async-trait = { workspace = true }
bytes = { workspace = true }
bytestring = { workspace = true, features = ["serde"] }
codederror = { workspace = true }
derive_builder = { workspace = true }
derive_more = { workspace = true }
drain = { workspace = true }
enum-map = { workspace = true, features = ["serde"] }
once_cell = { workspace = true }
schemars = { workspace = true, optional = true }
serde = { workspace = true }
serde_json = { workspace = true }
static_assertions = { workspace = true }
strum_macros = { workspace = true }
strum = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }


[dev-dependencies]
restate-core = { workspace = true, features = ["test-util"] }
restate-test-util = { workspace = true }

googletest = { workspace = true }
test-log = { workspace = true }
tracing-test = { workspace = true }
tracing-subscriber = { workspace = true }
tokio = { workspace = true, features = ["test-util"] }
