[package]
name = "restate-cli"
version = "0.0.1-dev"
authors = { workspace = true }
description = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
rust-version = { workspace = true }
publish = false
default-run = "restate"
build = "build.rs"

[features]
default = []

[dependencies]
clap = { version = "4.1", features = ["derive", "env"] }
tokio = { workspace = true }
tracing = { workspace = true }

[build-dependencies]
vergen = { version = "8.0.0", default-features = false, features = [
    "build",
    "git",
    "gitcl",
    "cargo",
] }

[lib]
bench = false

[[bin]]
name = "restate"
path = "src/main.rs"
