[package]
name = "restate-node"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[features]
default = []
options_schema = [
    "dep:schemars",
    "restate-admin/options_schema",
    "restate-meta/options_schema",
    "restate-node-ctrl/options_schema",
    "restate-worker/options_schema",
    "restate-cluster-controller/options_schema"]

[dependencies]

restate-admin = { workspace = true }
restate-bifrost = { workspace = true }
restate-cluster-controller = { workspace = true }
restate-meta = { workspace = true }
restate-node-ctrl = { workspace = true }
restate-node-ctrl-proto = { workspace = true }
restate-storage-rocksdb = { workspace = true }
restate-types = { workspace = true }
restate-worker = { workspace = true }

codederror = { workspace = true }
derive_builder = { workspace = true }
drain = { workspace = true }
futures = { workspace = true }
http = { workspace = true }
schemars = { workspace = true, optional = true }
serde = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tonic = { workspace = true }
tracing = { workspace = true }
