[package]
name = "restate-timer-queue"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
futures = { workspace = true }
tokio = { workspace = true }
