[package]
name = "restate-worker-api"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
restate-schema-api = { workspace = true, features = ["subscription"]}
restate-types = { workspace = true }

thiserror = { workspace = true }
