[package]
name = "restate-server"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false
description.workspace = true

[features]
default = []
console = [
    "tokio/full",
    "tokio/tracing",
    "restate-tracing-instrumentation/console-subscriber",
]
options_schema = [
    "dep:schemars",
    "restate-tracing-instrumentation/options_schema",
    "restate-meta/options_schema",
    "restate-worker/options_schema",
]

[dependencies]
restate-errors = { workspace = true, features = ["include_doc"] }
restate-fs-util = { workspace = true }
restate-meta = { workspace = true }
restate-tracing-instrumentation = { workspace = true, features = ["rt-tokio"] }
restate-types = { workspace = true }
restate-worker = { workspace = true }

clap = { version = "4.1", features = ["derive", "env"] }
codederror = { workspace = true }
derive_builder = { workspace = true }
drain = { workspace = true }
figment = { version = "0.10.8", features = ["env", "yaml"] }
futures-util = { workspace = true }
humantime = { workspace = true }
pin-project = { workspace = true }
schemars = { workspace = true, optional = true }
serde = { workspace = true }
serde_with = { workspace = true }
serde_yaml = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
