[package]
name = "restate-node-services"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[features]
default = []
clients = []
servers = []

[dependencies]
restate-node-protocol = { workspace = true }
restate-types = { workspace = true }

anyhow = { workspace = true, optional = true }
bytes = { workspace = true, optional = true }
prost = { workspace = true }
prost-types = { workspace = true }
thiserror = { workspace = true, optional = true }
tonic = { workspace = true, features = ["transport", "codegen", "prost"] }

[build-dependencies]
tonic-build = { workspace = true }
