[package]
name = "restate-test-util"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
assert2 = { workspace = true }
googletest = { workspace = true }
pretty_assertions = "1.3"
prost = { workspace = true, optional = true }
test-log = { version = "0.2.11", default-features = false, features = ["trace"] }

[dev-dependencies]
prost-types = { workspace = true }
