[package]
name = "restate-types"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[features]
default = []

mocks = ["rand"]
serde = ["dep:serde", "dep:serde_with"]
serde_schema = ["serde", "dep:schemars"]
tonic_conversions = ["dep:tonic"]
test-utils = []

[dependencies]
restate-base64-util = { workspace = true }

anyhow = { workspace = true }
base64 = { workspace = true }
bytes = { workspace = true }
bytestring = { workspace = true }
http = { workspace = true }
humantime = { workspace = true }
opentelemetry_api = { workspace = true }
rand = { workspace = true, optional = true }
schemars = { workspace = true, optional = true }
serde = { workspace = true, optional = true }
serde_with = { workspace = true, optional = true }
sha2 = { workspace = true }
sync_wrapper = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, default-features = false, features = ["time", "sync"]}
tonic = { workspace = true, optional = true }
tracing = { workspace = true }
tracing-opentelemetry = { workspace = true }
ulid = { workspace = true }
derive_more = { workspace = true }

base62 = { version = "2.0.2" }
num-traits = { version = "0.2.17" }
xxhash-rust = { version = "0.8", features = ["xxh3"] }

[dev-dependencies]
restate-test-util = { workspace = true }

rand = { workspace = true }
