[package]
name = "restate-errors"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[features]
default = []
include_doc = ["termimad"]

[dependencies]
codederror = { workspace = true }
paste = { workspace = true }
termimad = { version = "0.23", optional = true }
tracing = { workspace = true }

[dev-dependencies]
restate-test-util = { workspace = true }

thiserror = { workspace = true }
tracing-subscriber = { workspace = true }

