[package]
name = "restate-wal-protocol"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[features]
default = ["serde"]
serde = ["dep:serde", "dep:bincode", "enum-map/serde", "bytestring/serde", "restate-types/serde", "restate-invoker-api/serde", "restate-storage-api/serde"]
options_schema = ["dep:schemars"]

[dependencies]
restate-types = { workspace = true }
restate-storage-api = { workspace = true }
restate-invoker-api = { workspace = true }

anyhow = { workspace = true }
async-trait = { workspace = true }
bincode = { workspace = true, optional = true }
bytes = { workspace = true }
bytestring = { workspace = true }
codederror = { workspace = true }
derive_builder = { workspace = true }
derive_more = { workspace = true }
drain = { workspace = true }
enum-map = { version = "2.7.3" }
#futures = { workspace = true }
once_cell = { workspace = true }
schemars = { workspace = true, optional = true }
serde = { workspace = true, optional = true }
serde_json = { workspace = true }
static_assertions = { workspace = true }
strum_macros = { version = "0.26.1" }
strum = { version = "0.26.1" }
thiserror = { workspace = true }
tokio = { workspace = true }
#tokio-util = { workspace = true }
tracing = { workspace = true }


[dev-dependencies]
restate-test-util = { workspace = true }

googletest = { workspace = true }
test-log = { workspace = true }
tracing-test = { version = "0.2.4" }
tracing-subscriber = { workspace = true }
tokio = { workspace = true, features = ["test-util"] }
