[package]
name = "restate-core"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[features]
test-util = ["dep:rand"]

[dependencies]
restate-types = { workspace = true }
restate-node-protocol = { workspace = true }

anyhow = { workspace = true }
arc-swap = { workspace = true }
async-trait = { workspace = true }
derive_more = { workspace = true }
enum-map = { workspace = true }
futures = { workspace = true }
rand = { workspace = true, optional = true }
static_assertions = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tokio-util = { workspace = true }
tracing = { workspace = true }


[dev-dependencies]
restate-test-util = { workspace = true }

googletest = { workspace = true }
rand = { workspace = true }
test-log = { workspace = true }
tokio = { workspace = true, features = ["test-util"] }
tracing-subscriber = { workspace = true }
tracing-test = { workspace = true }

