[package]
name = "restate-network"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
restate-types = { workspace = true }
restate-errors = { workspace = true }

anyhow = { workspace = true }
bytes = { workspace = true }
drain = { workspace = true }
futures = { workspace = true }
pin-project = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
restate-test-util = { workspace = true }

tracing-subscriber = { workspace = true }

