[package]
name = "restate-network"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
restate-core = { workspace = true }
restate-errors = { workspace = true }
restate-node-protocol = { workspace = true }
restate-types = { workspace = true }
restate-wal-protocol = { workspace = true }

anyhow = { workspace = true }
async-trait = { workspace = true }
bytes = { workspace = true }
drain = { workspace = true }
futures = { workspace = true }
http = { workspace = true }
pin-project = { workspace = true }
static_assertions = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tonic = { workspace = true }
tower = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
restate-core = { workspace = true, features = ["test-util"] }
restate-test-util = { workspace = true }

test-log = { workspace = true }
tracing-subscriber = { workspace = true }
