name: Create new release

on:
  push:
    tags:
      - v**

jobs:
  run-tests:
    name: Test release
    uses: ./.github/workflows/ci.yml

  build-docker-image:
    name: Build release Docker image
    needs: [run-tests]
    uses: ./.github/workflows/docker.yml

  build-cli-binaries:
    name: Build release cli binaries
    needs: [run-tests]
    uses: ./.github/workflows/cli.yml

  create-release:
    name: Create release
    runs-on: ubuntu-latest
    needs: [build-docker-image, build-cli-binaries]

    steps:
      - name: Download cli binaries
        uses: actions/download-artifact@v3

      - name: Package cli binaries
        id: package-cli-binaries
        run: |
          for cli in restate-cli-*; do zip -j ${cli}.zip ${cli}/restate-cli; done
          echo "PACKAGES<<EOF" >> $GITHUB_OUTPUT
          ls -1 restate-cli-*.zip >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          # create a draft release which needs manual approval
          draft: true
          files: ${{ steps.package-cli-binaries.outputs.PACKAGES }}
            
